repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.9.9  # Match your local Ruff version
    hooks:
    -   id: ruff
        args: [--fix, --select=I]  # Run import sorting first
    -   id: ruff
        args: [--fix]  # Then run all other fixes